module Cl.Print where

-- pretty-printer generated by the BNF converter

import Cl.Abs
import Char

-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString i)



instance Print Id where
  prt i e = case e of
   Qname id0 id -> prPrec i 0 (concatD [prt 0 id0 , doc (showString "_") , prt 0 id])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Exp where
  prt i e = case e of
   Evar id -> prPrec i 1 (concatD [prt 0 id])
   Efun id -> prPrec i 1 (concatD [prt 0 id])
   Econ id -> prPrec i 1 (concatD [prt 0 id])
   Eapp exp0 exp -> prPrec i 0 (concatD [prt 0 exp0 , prt 1 exp])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Pat where
  prt i e = case e of
   Pvar id -> prPrec i 0 (concatD [prt 0 id])
   Pcon id pats -> prPrec i 0 (concatD [doc (showString "(") , prt 0 id , prt 0 pats , doc (showString ")")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Guard where
  prt i e = case e of
   Guard exps -> prPrec i 0 (concatD [doc (showString "|") , prt 0 exps])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Def where
  prt i e = case e of
   Def pat exp -> prPrec i 0 (concatD [prt 0 pat , doc (showString "=") , prt 0 exp])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Local where
  prt i e = case e of
   Loc defs -> prPrec i 0 (concatD [doc (showString "where") , prt 0 defs])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Clause where
  prt i e = case e of
   Cl id pats guards exp locals -> prPrec i 0 (concatD [prt 0 id , prt 0 pats , prt 0 guards , doc (showString "=") , prt 0 exp , prt 0 locals])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString "\n") , prt 0 xs])

instance Print Lit where
  prt i e = case e of
   Lpos exp0 exp -> prPrec i 0 (concatD [prt 0 exp0 , doc (showString "=") , prt 0 exp])
   Lneg exp0 exp -> prPrec i 0 (concatD [doc (showString "not") , doc (showString "(") , prt 0 exp0 , doc (showString "=") , prt 0 exp , doc (showString ")")])
   Linline id -> prPrec i 0 (concatD [prt 0 id])
   Lninline id -> prPrec i 0 (concatD [prt 0 id])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString "|") , prt 0 xs])

instance Print Pcl where
  prt i e = case e of
   PCl lits -> prPrec i 0 (concatD [prt 0 lits])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString "\n") , prt 0 xs])

instance Print PropCl where
  prt i e = case e of
   Property id ids pcls0 pcls -> prPrec i 0 (concatD [prt 0 id , prt 0 ids , prt 0 pcls0 , prt 0 pcls])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString "\n") , prt 0 xs])

instance Print Module where
  prt i e = case e of
   Mod clauses propcls -> prPrec i 0 (concatD [prt 0 clauses , doc (showString "\n-- Properties\n") , prt 0 propcls])



